spring.application.name=ms-autorizacion
server.port=8082

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.wzjfztuvpfcimmlgsqbm
spring.datasource.password=AduanaPro123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.sql.init.data-locations=

spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=bd_autorizacion

spring.flyway.enabled=true
spring.flyway.default-schema=bd_autorizacion
spring.flyway.schemas=bd_autorizacion
spring.flyway.locations=classpath:db/migration