CREATE SCHEMA IF NOT EXISTS bd_iam;

CREATE TABLE bd_iam.usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut VARCHAR(12) NOT NULL UNIQUE,
  nombres VARCHAR(20),
  apellido_paterno VARCHAR(20),
  apellido_materno VARCHAR(20),
  email VARCHAR(20) UNIQUE,
  telefono VARCHAR(15),
  password VARCHAR(15) NOT NULL,
  organismo VARCHAR(10),
  paso_asignado VARCHAR(30),
  activo BOOLEAN DEFAULT TRUE,
  ultimo_acceso TIMESTAMP,
  fecha_creacion TIMESTAMP
);

CREATE TABLE bd_iam.rol (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(30) NOT NULL
);

CREATE TABLE bd_iam.permiso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  descripcion VARCHAR(30)
);

-- TABLAS INTERMEDIAS
CREATE TABLE bd_iam.usuario_rol (
  id_usuario BIGINT NOT NULL REFERENCES bd_iam.usuario(id) ON DELETE CASCADE,
  id_rol BIGINT NOT NULL REFERENCES bd_iam.rol(id) ON DELETE CASCADE,
  PRIMARY KEY (id_usuario, id_rol)
);

CREATE TABLE bd_iam.rol_permiso (
  id_rol BIGINT NOT NULL REFERENCES bd_iam.rol(id) ON DELETE CASCADE,
  id_permiso BIGINT NOT NULL REFERENCES bd_iam.permiso(id) ON DELETE CASCADE,
  PRIMARY KEY (id_rol, id_permiso)
);